---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mongo-deployment
 namespace: mongo
 labels:
   k8s-app: mongo
spec:
  progressDeadlineSeconds: 420
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
              name: http
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 60
          resources:
            limits:
              cpu: 600m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: mongo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 27017
    protocol: TCP
  selector:
    k8s-app: mongo